output "instruction" {
  value = "Please see ./snowflake_credentials.txt for Snowflake to S3 credentials and instructions."
}

output "snowflake_to_s3_bucket" {
  description = "Name of the S3 bucket used to store Snowflake CUR reports"
  value       = aws_s3_bucket.snowflake_cur_reports.bucket
}
output "snowflake_aws_access_key_id" {
  description = "AWS access key ID for Snowflake user (use in Snowflake STAGE)"
  value       = aws_iam_access_key.snowflake_rw_key.id
}

output "snowflake_aws_secret_access_key" {
  description = "AWS secret access key for Snowflake user (use in Snowflake STAGE)"
  value       = aws_iam_access_key.snowflake_rw_key.secret
  sensitive   = true
}

resource "local_file" "snowflake_rw_credentials" {
  filename = "${path.module}/snowflake_credentials.txt"

  content = <<EOF
# ===============================
#  Snowflake → S3 Credentials
# ===============================

S3_BUCKET = "${aws_s3_bucket.snowflake_cur_reports.bucket}"
S3_URL    = "s3://${aws_s3_bucket.snowflake_cur_reports.bucket}/"

AWS_ACCESS_KEY_ID     = "${aws_iam_access_key.snowflake_rw_key.id}"
AWS_SECRET_ACCESS_KEY = "${aws_iam_access_key.snowflake_rw_key.secret}"

# Paste these into Snowflake:
#
# CREATE OR REPLACE STAGE cur_s3_stage
#   URL = 's3://${aws_s3_bucket.snowflake_cur_reports.bucket}/'
#   CREDENTIALS = (
#     AWS_KEY_ID='${aws_iam_access_key.snowflake_rw_key.id}',
#     AWS_SECRET_KEY='${aws_iam_access_key.snowflake_rw_key.secret}'
#   );
#
EOF

  #   file_permission = "0600"
}

output "cloudsibyl_read_role_arn" {
  description = "IAM Role ARN to paste into the CloudSibyl console"
  value       = aws_iam_role.cloudsibyl_read_role.arn
}

resource "local_file" "cloudsibyl_role_info" {
  filename = "${path.module}/cloudsibyl_role_info.txt"

  content = <<EOF
# ============================================
#  CloudSibyl AWS Integration – Required Fields
# ============================================

ARN         = ${aws_iam_role.cloudsibyl_read_role.arn}
ExternalId  = ${var.cloudsibyl_external_id}
BucketName  = ${aws_s3_bucket.snowflake_cur_reports.bucket}

# Paste these three values into the CloudSibyl console when adding an AWS provider.
#
# File generated by Terraform on: ${timestamp()}
EOF
}
